name: quran_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Features
  home:
    path: features/home
  splash:
    path: features/splash
  detail_surah:
    path: features/detail_surah
  bookmark:
    path: features/bookmark

  # Domains
  quran:
    path: domains/quran

  # Resources
  resources:
    path: resources/resources

  # Shared Libraries
  common:
    path: shared_libraries/common
  core:
    path: shared_libraries/core
  dependencies:
    path: shared_libraries/dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/